/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancesystem;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;
/**
 *
 * @author User
 */
public class Ad_ModifyAtt extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAtt
     */
    public Ad_ModifyAtt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        butBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabStu = new javax.swing.JTable();
        butSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comIntake = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comDay = new javax.swing.JComboBox<>();
        comMonth = new javax.swing.JComboBox<>();
        butGetList = new javax.swing.JButton();
        labModuleName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modify Attendance");

        butBack.setText("Back");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        TabStu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TabStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabStu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(TabStu);
        if (TabStu.getColumnModel().getColumnCount() > 0) {
            TabStu.getColumnModel().getColumn(0).setMaxWidth(100);
            TabStu.getColumnModel().getColumn(1).setMinWidth(200);
            TabStu.getColumnModel().getColumn(1).setMaxWidth(600);
        }

        butSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butSave.setText("Save");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2017" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date:");
        jLabel4.setToolTipText("");

        comIntake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UC1F1701IT", "UCDF1509BIT", "UC2F1704BIS", "UCDF1601BIT", "UC2F1702ISS", "UC1F1703EBM" }));
        comIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comIntakeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Module:");
        jLabel3.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Intake:");

        comDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09" }));

        butGetList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butGetList.setText("Get List");
        butGetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGetListActionPerformed(evt);
            }
        });

        labModuleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labModuleName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "VBN", "MTK", "EBM", "CACC", "SEC" }));
        labModuleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labModuleNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(comYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comIntake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labModuleName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butGetList)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(butGetList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(butSave)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(butBack)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        this.setVisible(false);
        
        Ad_Main admain = new Ad_Main();
        admain.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_butBackActionPerformed

    private void comIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comIntakeActionPerformed
 
    }//GEN-LAST:event_comIntakeActionPerformed

    private void butGetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGetListActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tm = (DefaultTableModel) TabStu.getModel();
        tm.setRowCount(0);
        String intake = comIntake.getSelectedItem().toString();
        String module = labModuleName.getSelectedItem().toString();
        String date = comYear.getSelectedItem().toString() + "-" + comMonth.getSelectedItem().toString() + "-" + comDay.getSelectedItem().toString();
        

        try {
            if (intake.equals("UC1F1701IT")) {
                BufferedReader in = new BufferedReader(new java.io.FileReader(intake+module+date+".txt"));
                String line;

                while ((line = in.readLine()) != null) {

                    tm.addRow(line.split(";"));
                    //  JOptionPane.showMessageDialog(null,line.split("/"));

                }
                in.close();
            }
            if (intake.equals("UCDF1509BIT")) {
                BufferedReader in = new BufferedReader(new java.io.FileReader(intake+module+date+".txt"));
                String line;
                while ((line = in.readLine()) != null) {

                    tm.addRow(line.split(";"));
                    //  JOptionPane.showMessageDialog(null,line.split("/"));

                }
                in.close();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Please select an intake.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        TableColumn col = TabStu.getColumnModel().getColumn(2);
        JComboBox com = new JComboBox();
        
        com.addItem("Absent");
        com.addItem("Absent with reason");
        col.setCellEditor(new DefaultCellEditor(com));
    }//GEN-LAST:event_butGetListActionPerformed

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) TabStu.getModel();
        TableColumn col = TabStu.getColumnModel().getColumn(2);
        String today = comYear.getSelectedItem().toString() + "-" + comMonth.getSelectedItem().toString() + "-" + comDay.getSelectedItem().toString();

        JComboBox com = new JComboBox();
        com.addItem("Present");
        com.addItem("Late");
        com.addItem("Absent");
        col.setCellEditor(new DefaultCellEditor(com));

        String[] records = null;

        String att = com.getSelectedItem().toString();
        String intake = comIntake.getSelectedItem().toString();
        String module = labModuleName.getSelectedItem().toString();
     
        String line;

        try
        {

            File lect = new File(intake+module+today+".txt");
            
                lect.createNewFile();
                PrintWriter os = new PrintWriter(lect);
                BufferedWriter  f = new BufferedWriter (new FileWriter(intake+module+today+".txt",false));

                for (int row = 0; row < TabStu.getRowCount(); row++) {
                    //f.newLine();
                    for (int cols = 0; cols < TabStu.getColumnCount(); cols++) {

                        f.write((String) TabStu.getValueAt(row, cols)+";");
                        //f.write(TabStu.getValueAt(0 , 0)+ ";" +TabStu.getValueAt(0 , 1) + ";"+TabStu.getValueAt(0 , 2)); //+ ";" +
                        //name + ";" + att +  "\n");
                }
                f.write("");
                f.newLine();

            }
            //f.write(intake + ";" + module + ";" + time + ";" + TabStu.getValueAt(0 , 0)+ ";" +TabStu.getValueAt(0 , 0) + ";"+TabStu.getValueAt(0 , 2)); //+ ";" +
            //name + ";" + att +  "\n");
        f.close();
        JOptionPane.showMessageDialog(null, "Successfully Saved","Success",JOptionPane.INFORMATION_MESSAGE);
        

        }

        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"Can't find a text file");
        }
    }//GEN-LAST:event_butSaveActionPerformed

    private void labModuleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labModuleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labModuleNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ad_ModifyAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ad_ModifyAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ad_ModifyAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ad_ModifyAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ad_ModifyAtt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabStu;
    private javax.swing.JButton butBack;
    private javax.swing.JButton butGetList;
    private javax.swing.JButton butSave;
    private javax.swing.JComboBox<String> comDay;
    private javax.swing.JComboBox<String> comIntake;
    private javax.swing.JComboBox<String> comMonth;
    private javax.swing.JComboBox<String> comYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> labModuleName;
    // End of variables declaration//GEN-END:variables
}
