/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancesystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class L_ViewStudents extends javax.swing.JFrame {
    
    /**
     * Creates new form L_ViewStudents
     */
    public L_ViewStudents() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        butView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabStu = new javax.swing.JTable();
        butBack1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labModule = new javax.swing.JLabel();
        comIntake = new javax.swing.JComboBox<>();
        labModuleName = new javax.swing.JLabel();
        Modu = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Students");

        butView.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butView.setText("View");
        butView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butViewActionPerformed(evt);
            }
        });

        TabStu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "UserID", "Name", "Nationality", "Phone No.", "Email Add."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabStu);
        if (TabStu.getColumnModel().getColumnCount() > 0) {
            TabStu.getColumnModel().getColumn(0).setMinWidth(50);
            TabStu.getColumnModel().getColumn(0).setMaxWidth(50);
            TabStu.getColumnModel().getColumn(1).setMinWidth(120);
            TabStu.getColumnModel().getColumn(1).setMaxWidth(120);
            TabStu.getColumnModel().getColumn(2).setMinWidth(100);
            TabStu.getColumnModel().getColumn(2).setMaxWidth(100);
            TabStu.getColumnModel().getColumn(3).setMinWidth(100);
            TabStu.getColumnModel().getColumn(3).setMaxWidth(100);
            TabStu.getColumnModel().getColumn(4).setMinWidth(190);
            TabStu.getColumnModel().getColumn(4).setMaxWidth(190);
        }

        butBack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butBack1.setText("Back");
        butBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBack1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labModule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labModule.setText("Module:");

        comIntake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UC1F1701IT", "UCDF1509BIT" }));
        comIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comIntakeActionPerformed(evt);
            }
        });

        labModuleName.setBackground(new java.awt.Color(153, 153, 153));
        labModuleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labModuleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labModuleName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labModuleName.setMinimumSize(new java.awt.Dimension(10, 4));

        Modu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Modu.setText("Intake:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modu)
                    .addComponent(labModule))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comIntake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modu)
                    .addComponent(comIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labModule)
                    .addComponent(labModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(butView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(butBack1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(butBack1)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comIntakeActionPerformed
        if(comIntake.getSelectedItem().toString().equals("UC1F1701IT")){
        labModuleName.setText("VBN");};
        
        if(comIntake.getSelectedItem().toString().equals("UCDF1509BIT")){
        labModuleName.setText("MTK");}
        
    

        // TODO add your handling code here:
    }//GEN-LAST:event_comIntakeActionPerformed

    private void butViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butViewActionPerformed
        // TODO add your handling code here:
        TabStu.setVisible(true);
        DefaultTableModel tm = (DefaultTableModel) TabStu.getModel();
        tm.setRowCount(0);
        String intake = comIntake.getSelectedItem().toString();
        String module = labModuleName.getText();
        try
        {
            if (intake.equals("UC1F1701IT")) {
            BufferedReader in = new BufferedReader(new java.io.FileReader("UC1F1701IT.txt"));
            String line;
            while ((line = in.readLine()) != null)
            {

                tm.addRow(line.split(";"));
                //  JOptionPane.showMessageDialog(null,line.split("/"));

            }
            in.close();}
            if (intake.equals("UCDF1509BIT")) {
            BufferedReader in = new BufferedReader(new java.io.FileReader("UCDF1509BIT.txt"));
            String line;
            while ((line = in.readLine()) != null)
            {

                tm.addRow(line.split(";"));
                //  JOptionPane.showMessageDialog(null,line.split("/"));

            }
            in.close();}
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null, "Please select an intake.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butViewActionPerformed

    private void butBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        L_Main smain = new L_Main();
        smain.setVisible(true);
    }//GEN-LAST:event_butBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L_ViewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L_ViewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L_ViewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L_ViewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L_ViewStudents().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modu;
    private javax.swing.JTable TabStu;
    private javax.swing.JButton butBack1;
    private javax.swing.JButton butView;
    private javax.swing.JComboBox<String> comIntake;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labModule;
    private javax.swing.JLabel labModuleName;
    // End of variables declaration//GEN-END:variables
}
